FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY tailwind*.config.js ./
COPY postcss*.config.js ./
COPY vite*.config.ts ./
COPY tsconfig*.json ./

RUN npm install

COPY . .

# Expose the correct port
EXPOSE 5173

# Update the command to use host flag
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]