"""Add UUID column to Wine model

Revision ID: dd8b8c996d15
Revises: 
Create Date: 2025-01-03 15:33:49.464789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8b8c996d15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('full_wine_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('vineyard', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('average_rating', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vivino_database_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vivino_database_table',
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vineyard', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('average_rating', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('price', sa.REAL(), autoincrement=False, nullable=True)
    )
    op.drop_table('full_wine_list')
    # ### end Alembic commands ###
